spring.application.name=backend

# PostgreSQL Database Configuration (Portainer)
spring.datasource.url=jdbc:postgresql://192.168.31.229:15432/helphealth
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SQLite Database Location for the Export Routine
helphealth.sqlite.db-path=./anvisa_app_database.db

